// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.UserDetailsJsonTypes;

namespace AngelList.JsonTypes.UserDetailsJsonTypes
{

    public class Investment
    {

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("quality")]
        public int Quality { get; set; }
    }

}
