// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.UserDetailsJsonTypes;

namespace AngelList.JsonTypes.UserDetailsJsonTypes
{

    public class InvestorDetails
    {

        [JsonProperty("startups_per_year")]
        public string StartupsPerYear { get; set; }

        [JsonProperty("average_amount")]
        public string AverageAmount { get; set; }

        [JsonProperty("accreditation")]
        public string Accreditation { get; set; }

        [JsonProperty("markets")]
        public Market[] Markets { get; set; }

        [JsonProperty("locations")]
        public Location2[] Locations { get; set; }

        [JsonProperty("investments")]
        public Investment[] Investments { get; set; }
    }

}
