// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.StartupJsonTypes;

namespace AngelList.JsonTypes.StartupJsonTypes
{

    public class Screenshot
    {

        [JsonProperty("thumb")]
        public string Thumb { get; set; }

        [JsonProperty("original")]
        public string Original { get; set; }
    }

}
