// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.StartupJsonTypes;

namespace AngelList.JsonTypes
{
    [DataContract]
    public class Startup
    {

        [JsonProperty("id")]
        [DataMember(Name = "id")]
        public int Id { get; set; }

        [JsonProperty("hidden")]
        [DataMember(Name = "hidden")]
        public bool Hidden { get; set; }

        [JsonProperty("community_profile")]
        [DataMember(Name = "community_profile")]
        public bool CommunityProfile { get; set; }

        [JsonProperty("name")]
        [DataMember(Name = "name")]
        public string Name { get; set; }

        [JsonProperty("angellist_url")]
        [DataMember(Name = "angellist_url")]
        public string AngellistUrl { get; set; }

        [JsonProperty("logo_url")]
        [DataMember(Name = "logo_url")]
        public string LogoUrl { get; set; }

        [JsonProperty("thumb_url")]
        [DataMember(Name = "thumb_url")]
        public string ThumbUrl { get; set; }

        [JsonProperty("quality")]
        [DataMember(Name = "quality")]
        public int Quality { get; set; }

        [JsonProperty("product_desc")]
        [DataMember(Name = "product_desc")]
        public string ProductDesc { get; set; }

        [JsonProperty("high_concept")]
        [DataMember(Name = "high_concept")]
        public string HighConcept { get; set; }

        [JsonProperty("follower_count")]
        [DataMember(Name = "follower_count")]
        public int FollowerCount { get; set; }

        [JsonProperty("company_url")]
        [DataMember(Name = "company_url")]
        public string CompanyUrl { get; set; }

        [JsonProperty("created_at")]
        [DataMember(Name = "created_at")]
        public string CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        [DataMember(Name = "updated_at")]
        public string UpdatedAt { get; set; }

        [JsonProperty("twitter_url")]
        [DataMember(Name = "twitter_url")]
        public string TwitterUrl { get; set; }

        [JsonProperty("blog_url")]
        [DataMember(Name = "blog_url")]
        public string BlogUrl { get; set; }

        [JsonProperty("video_url")]
        [DataMember(Name = "video_url")]
        public string VideoUrl { get; set; }

        [JsonProperty("markets")]
        [DataMember(Name = "markets")]
        public Market[] Markets { get; set; }

        [JsonProperty("locations")]
        [DataMember(Name = "locations")]
        public Location[] Locations { get; set; }

        [JsonProperty("crunchbase_url")]
        [DataMember(Name = "crunchbase_url")]
        public string CrunchbaseUrl { get; set; }

        [JsonProperty("company_type")]
        [DataMember(Name = "company_type")]
        public CompanyType[] CompanyType { get; set; }

        [JsonProperty("status")]
        [DataMember(Name = "status")]
        public Status Status { get; set; }

        [JsonProperty("screenshots")]
        [DataMember(Name = "screenshots")]
        public Screenshot[] Screenshots { get; set; }
    }

}
