// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.UserRoleJsonTypes;

namespace AngelList.JsonTypes
{
    [DataContract]
    public class UsersRolesResponse
    {
        [DataMember(Name = "startup_roles")]
        [JsonProperty("startup_roles")]
        public StartupRole[] StartupRoles { get; set; }

        [DataMember(Name = "total")]
        [JsonProperty("total")]
        public int Total { get; set; }

        [DataMember(Name = "per_page")]
        [JsonProperty("per_page")]
        public int PerPage { get; set; }

        [DataMember(Name = "page")]
        [JsonProperty("page")]
        public int Page { get; set; }

        [DataMember(Name = "last_page")]
        [JsonProperty("last_page")]
        public int LastPage { get; set; }
    }

}
