// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.UserRoleJsonTypes;

namespace AngelList.JsonTypes.UserRoleJsonTypes
{
    [DataContract]
    public class StartupRole
    {

        [JsonProperty("id")]
        [DataMember(Name = "id")]
        public int Id { get; set; }

        [JsonProperty("role")]
        [DataMember(Name = "role")]
        public string Role { get; set; }

        [JsonProperty("created_at")]
        [DataMember(Name = "created_at")]
        public string CreatedAt { get; set; }

        [JsonProperty("started_at")]
        [DataMember(Name = "started_at")]
        public string StartedAt { get; set; }

        [JsonProperty("ended_at")]
        [DataMember(Name = "ended_at")]
        public object EndedAt { get; set; }

        [JsonProperty("confirmed")]
        [DataMember(Name = "confirmed")]
        public bool Confirmed { get; set; }

        [JsonProperty("tagged")]
        [DataMember(Name = "tagged")]
        public Tagged Tagged { get; set; }

        [JsonProperty("startup")]
        [DataMember(Name = "startup")]
        public Startup Startup { get; set; }
    }

}
