// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using AngelList.JsonTypes.UserRoleJsonTypes;

namespace AngelList.JsonTypes.UserRoleJsonTypes
{
    [DataContract]
    public class Startup
    {

        [JsonProperty("id")]
        [DataMember(Name = "id")]
        public int Id { get; set; }

        [JsonProperty("hidden")]
        [DataMember(Name = "hidden")]
        public bool Hidden { get; set; }

        [JsonProperty("community_profile")]
        [DataMember(Name = "community_profile")]
        public bool CommunityProfile { get; set; }

        [JsonProperty("name")]
        [DataMember(Name = "name")]
        public string Name { get; set; }

        [JsonProperty("angellist_url")]
        [DataMember(Name = "angellist_url")]
        public string AngellistUrl { get; set; }

        [JsonProperty("logo_url")]
        [DataMember(Name = "logo_url")]
        public string LogoUrl { get; set; }

        [JsonProperty("thumb_url")]
        [DataMember(Name = "thumb_url")]
        public string ThumbUrl { get; set; }

        [JsonProperty("quality")]
        [DataMember(Name = "quality")]
        public int Quality { get; set; }

        [JsonProperty("product_desc")]
        [DataMember(Name = "product_desc")]
        public string ProductDesc { get; set; }

        [JsonProperty("high_concept")]
        [DataMember(Name = "high_concept")]
        public string HighConcept { get; set; }

        [JsonProperty("follower_count")]
        [DataMember(Name = "follower_count")]
        public int FollowerCount { get; set; }

        [JsonProperty("company_url")]
        [DataMember(Name = "company_url")]
        public string CompanyUrl { get; set; }

        [JsonProperty("created_at")]
        [DataMember(Name = "created_at")]
        public string CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        [DataMember(Name = "updated_at")]
        public string UpdatedAt { get; set; }
    }

}
